### ISSUE TITLE
Move to celery's organization

### ISSUE THREAD

**Issue by thedrow** [celery/pytest-celery#1]
Since this is an official celery project now, we should move it to Celery's organization.

**Comment by graingert** [comment]
@thedrow I assumed inviting you to this repo would allow you to move it - but I think I need to create an org, and give you admin in that org

**Comment by graingert** [comment]
@thedrow you're now invited as an "Owner" to https://github.com/tmp-org-to-move-pytest-celery-to-celery/ you should be able to initiate the transfer from [The Danger Zone](https://github.com/tmp-org-to-move-pytest-celery-to-celery/pytest-celery/settings#danger-zone)
