### ISSUE TITLE
Adding a basic Readme for better describing the project

### ISSUE THREAD

**Issue by auvipy** [celery/pytest-celery#87]
I might start a draft one unless otherwise Nusnus add one

**Comment by Nusnus** [comment]
@auvipy I have a very strict working plan to run as efficiently as possible.
Please let me get the first version out under my plans. As you can see the results are coming up slowly, I got it bro - leave it 100% to me please.

**Comment by auvipy** [comment]
OK

**Comment by Nusnus** [comment]
I promise to help you catch up @auvipy - I just need to ensure the first version is out correctly as this is a huge change!
I'll contact you for a zoom call when it's ready ❤️

**Comment by auvipy** [comment]
I hope the issue didn't offend you. Although it was opened for request purposes. But I guess the wording might seem pushy? Although that was not the intention at all. I hope this Won't distract you.

**Comment by Nusnus** [comment]
> I hope the issue didn't offend you. Although it was opened for request purposes. But I guess the wording might seem pushy? Although that was not the intention at all. I hope this Won't distract you.

Haha we already know each other bro, all good! @auvipy 
I am just so deeply invested in this project that I am on a momentum and the README is more closer to the end, once the core-features are proven to work hehe.. So I am running with the development super fast and I try to discipline myself to be very efficient which might lead to responses such as mine above.

We're both trying to do the best for this organization my friend so I filter everything under these assumptions and take it all positively, I am just emotional as this is the biggest project of my life so far and I want to do my best!

**Comment by auvipy** [comment]
You are doing great. Dont worry much brother. For mental support I will be with you. You are goin to rock this one too

**Comment by Nusnus** [comment]
> You are doing great. Dont worry much brother. For mental support I will be with you. You are goin to rock this one too

Thank you man! I really appreciate it 🙏
